apiVersion: v1
kind: Service
metadata:
  name: jenkins_helm
  namespace: jenkins_helm
spec:
  ports:
    - name: master
      port: {{ index .Values "containerPort" "http-port" }}
      targetPort: {{ index .Values "containerPort" "http-port" }}
    - name: slave
      port: {{ index .Values "containerPort" "jnlp-port" }}
      targetPort: {{ index .Values "containerPort" "jnlp-port" }}
  selector:
    app: jenkins_helm
